# Generated by Django 4.1.2 on 2022-10-22 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='guest',
            old_name='guest_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='movie',
            old_name='movie_name',
            new_name='name',
        ),
    ]
