# Generated by Django 4.1.2 on 2022-10-23 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_rename_guest_name_guest_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='name',
            new_name='movie',
        ),
    ]
